if(C4UseNSIS)
  set(CPACK_GENERATOR "NSIS")
else(C4UseNSIS)
  set(CPACK_GENERATOR "ZIP")
endif(C4UseNSIS)

set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${CMAKE_PROJECT_VERSION})
set(CPACK_PACKAGE_VENDOR "My Games" )
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY ${CMAKE_PROJECT_NAME})
set(CPACK_IGNORE_FILES "\.psd$;/CVS/;/\.svn/;/\.git/;\.swp$;/CMakeLists.txt.user;\.#;/#;\.tar.gz$;/CMakeFiles/;CMakeCache.txt;\.qm$;/build/;\.diff$;.DS_Store'")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
set(CPACK_SOURCE_IGNORE_FILES ${CPACK_IGNORE_FILES})

# Load packaging facilities.
include(CPack)
#set(CPACK_NSIS_INSTALLED_ICON_NAME "INSTALLEDICON.ico")
#set(CPACK_NSIS_HELP_LINK ${HELP_URL})
#set(CPACK_NSIS_URL_INFO_ABOUT ${ABOUT_URL})
#set(CPACK_NSIS_CONTACT ${DEV_EMAIL})

ADD_CUSTOM_TARGET( Bundle COMMAND "${CMAKE_CPACK_COMMAND}" COMMENT "Running CPack. Please wait..." )